export const GET_USER_PROFILE = "GET_USER_PROFILE";

export const GET_USER_ACCESS_TOKEN = "GET_USER_ACCESS_TOKEN";

export const USER_AUTH = "USER_AUTH";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAILED = "USER_AUTH_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";
